### PR TITLE
[Improve] Add Batch Enable/Disable for Selectors and Rules

### PR DESCRIPTION
**Pull request by VampireAchao**
https://github.com/apache/shenyu-dashboard/issues/451

### CODE REVIEW

**Comment by VampireAchao** [comment]
Will change to switch after select

**Comment by kerwin612** [comment]
image
Adhering to the principle that "page layout design and UI interaction experience should be as consistent as possible," I suggest combining the two buttons into one, just as this feature is implemented on other pages.

**Review by kerwin612 — CHANGES_REQUESTED** [review]
image
Adhering to the principle that "page layout design and UI interaction experience should be as consistent as possible," I suggest combining the two buttons into one, just as this feature is implemented on other pages.

**Comment by VampireAchao** [comment]
Okay, I'll modifiy these. 🐱

**Review by kerwin612 — APPROVED** [review]

**Pull request merged**
