### PR TITLE
refactor: form style optimization, form field localization and logic modification

### PR DESCRIPTION
**Pull request by eurecalulu**
- related to https://github.com/apache/shenyu/issues/4534
- This pr mainly made the following changes：

1.  refactor the formatTimestamp function

2. form localization and optimization:
配置
选择器

### CODE REVIEW

**Review by li-keguo — APPROVED** [review]

**Comment by li-keguo** [comment]
Thank you for your contribution～

**Comment by li-keguo** [comment]
Updates can be packaged to admin

**Comment by li-keguo** [comment]
You can add some tips to the page to guide users to configure and use

**Comment by eurecalulu** [comment]
> Updates can be packaged to admin

Thank you for your suggestion, the front-end code has been packaged into the back-end shenyu-admin and merged

**Comment by eurecalulu** [comment]
> You can add some tips to the page to guide users to configure and use

Thank you for your advice, I have written a document and am going to submit it to shenyu-website later.

**Pull request merged**
