### PR TITLE
fixed #408

### LINKED ISSUE #408: [bug] /config/dict page exception
bug
After mouse hovering over the specified line, there are multiple lines highlighted at the same time

### PR DESCRIPTION
**Pull request by kerwin612**
fixed
The unique keys of the list should be consistent with the database

### CODE REVIEW

**Comment by dengliming** [comment]
I don't see the difference now, the id itself is unique.

**Comment by kerwin612** [comment]
> I don't see the difference now, the id itself is unique.

Can see my screenshot, in the h2 db, the id of this table is not unique, you can switch to the h2 db, You can find the problem mentioned in issue!

**Comment by kerwin612** [comment]
Because `shenyu_dict` table does not explicitly limit the `ID` must be unique, but by creating a unique key (**UNIQUE KEY `dict_type_dict_code_dict_name` (`type`,`dict_code`,`dict_name`)**) to ensure the uniqueness of the data;   
so there are duplicate IDs in sql scripts (apache/shenyu#5479);   
so in order to be compatible with previous data, I suggest that the front-end keep synchronization with the back-end, and replace the `ID` with a `unique key`;

**Comment by kerwin612** [comment]
By sql constraint on the backend, ensure that ID is unique, so there is no need to modify the frontend, so close this PR
see: apache/shenyu#5479 , apache/shenyu#5481

**Pull request closed without merging**
